#!/bin/bash
# sidfax v1.1-dev
# 30.04.2013
# (c) Pasquale Fiorillo < info @ pasqualefiorillo.it > 2013
# 
# Based on:
# email2fax 1.2 (http://wpkg.org/email2fax/)
# 05.02.2006
# This script allows you to send faxes through your Asterisk box.
# It converts an email with either a PDF or TIFF attachment to an email with a *right*
# TIFF format, and then passes it to Asterisk, which does the fax delivery.
# (c) Tomasz Chmielewski < tch @ wpkg . org > 2005-2006
# License: GPLv2

# Variables you might want to change

FAXMAIL="FAX Server <mailer@aacom.co.il>"		# email from which confirmations are sent

CHANNEL="IAX2/issabelsparrow"								# Channel you use for calling out (you probably have to
												# consult your /etc/asterisk/zapata.conf file)

LOGFILE=/var/log/asterisk/faxlog				# where to log

TMPDIR=/tmp/email2fax							# dir for temp files; must be writable by asterisk user

MAXAGE=60										# how long to keep temp files, including tiff files needed by 
												# Asterisk to send faxes; in minutes.
												# The reason for keeping these files so long is that 
												# Asterisk may not be able to send all faxes immediately.
						

# Variables that are probably OK for most systems

ASTERISKUSER=asterisk				# user under which asterisk is running; 
												# for most installations it should be "asterisk"

OUTGOINGDIR=/var/spool/asterisk/outgoing		# asterisk "outgoing" directory; for most installations
												# it should be /var/spool/asterisk/outgoing


# You probably don't have to change anything below...

DATADIR=$TMPDIR/`date +%s-%N`
EMAILFILE=$DATADIR/emailfile.eml
MESSAGEFILE=$DATADIR/message.txt


DATETIME=`date +"%A, %B %d %Y, at %R:%S"` 	# date put in email confirmations
#DATETIME=`date +"%A, %B %d %Y, at %r"`  	# date put in email confirmations, different format

VERSION="sidfax v1.1-dev"					# version



# check how we are started, print help if pipe wasn't used
[ -p /dev/stdin ]
[ $? -eq 1 ] && EMPTY=1 && cat <<EOF
$VERSION, email to fax gateway for Asterisk

Usage:

"piped message" | email2fax [OPTIONS]

Options:
--nomail	don't send a confirmation email (default: send confirmation email)
--nodelete	don't delete temporary files (default: delete temporary files)
--nofax		don't send the fax (default: send fax)
--debug		enable debug logging

Email has to contain either one PDF attachment OR one TIFF attachment, and
a destination fax number as a subject.

Examples:

This one sends a fax from the command line, and enables debug logging:

cat message.eml | sudo -u asterisk email2fax --debug


This one enables debug logging, doesn't send a confirmation email, 
doesn't delete temporary files, and doesn't send a fax (useful for testing etc.):

cat message.eml | sudo -u asterisk email2fax --debug --nomail --nodelete --nofax


This entry in .procmailrc located in asterisk home directory intercepts all emails
to asterisk, and passes them to email2fax:

:0fw
| /usr/local/bin/email2fax


By default, email2fax logs ALL messages to $LOGFILE, and saves temporary files in $TMPDIR.
These paths, along with several different variables, can be changed
at the beginning of this script ($0).

See http://wpkg.org/email2fax for updates, bug reports, and answers.

EOF

[ "$EMPTY" == "1" ] && exit 0

cat <<EOF >> $LOGFILE
--------------------------------------------------------------
$VERSION started on $DATETIME with options:

   $0 $@

EOF

# Check the error code and make a proper action



# Delete temporary files if requested
del_temp()
{

  echo "Removing old temporary files" >>$LOGFILE
  find $TMPDIR/* -type d -mmin +$MAXAGE -exec rm -fvr {} \; &>/dev/null
  find $TMPDIR/* -type d -mmin +$MAXAGE -exec rm -fvr {} \; >>$LOGFILE
  find /var/spool/asterisk/fax-outgoing/* -type f -mmin +$MAXAGE -exec rm -fvr {} \; >>$LOGFILE
  
  echo >>$LOGFILE

}

# By default, our internal "error code" should be 0
ERRORCODE=0

# Check who we are; log an error and quit if we're not the same user asterisk runs
#if [ $ASTERISKUSER != `whoami` ] ; then
#echo "asterisk user ($ASTERISKUSER) different from the user which started email2fax (`whoami`), sending faxes won't work, can't continue!" >>$LOGFILE
#ERRORCODE=2
#fi

# Make sure temp dir exists and is writable
mkdir -p $DATADIR
if [ $? -ne 0 ] ; then
echo "$DATADIR not writable, can't continue!" >>$LOGFILE
ERRORCODE=2
fi

# Check if tiff2ps (should be in libtiff package) is available
if [ `which tiff2ps &>/dev/null ; echo $?` -ne 0 ] ; then
echo "tiff2ps not available (should be in libtiff package): format conversion not possible, can't continue!" >>$LOGFILE
ERRORCODE=2
fi

# Check if gs program is installed
if [ `gs -version | grep Ghostscript &>/dev/null ; echo $?` -ne 0 ] ; then
echo "Ghostscript is not installed: format conversion not possible, can't continue!" >>$LOGFILE
ERRORCODE=2
fi

# Check if "ripmime" program is installed
if [ `which ripmime &>/dev/null ; echo $?` -ne 0 ] ; then
echo "ripmime is not installed: can't extract attachments, can't continue!" >>$LOGFILE
ERRORCODE=2
fi

# Read flags and set appropriate behaviour

[ `echo $@ | grep -i -q '\-\-nomail' ; echo $?` -eq 0 ] && NOMAIL=1 || NOMAIL=0
[ `echo $@ | grep -i -q '\-\-nodelete' ; echo $?` -eq 0 ] && NODELETE=1 || NODELETE=0
[ `echo $@ | grep -i -q '\-\-nofax' ; echo $?` -eq 0 ] && NOFAX=1 || NOFAX=0
[ `echo $@ | grep -i -q '\-\-debug' ; echo $?` -eq 0 ] && DEBUG=1 || DEBUG=0

UNKNOWN_FLAGS=`echo $@ | sed -e "s/--nomail//gI" -e "s/--nodelete//gI" -e "s/--nofax//gI" -e "s/--debug//gI"`
[ -z $UNKNOWN_FLAGS ]
[ $? -ne 0 ] && echo "WARNING: unknown flags: $UNKNOWN_FLAGS" >>$LOGFILE

cat <<EOF >>$LOGFILE
Variables used:

FAXMAIL:      $FAXMAIL
LOGFILE:      $LOGFILE
VERSION:      $VERSION
TMPDIR:       $TMPDIR
DATADIR:      $DATADIR
EMAILFILE:    $EMAILFILE
MESSAGEFILE:  $MESSAGEFILE
DATETIME:     $DATETIME

EOF

# Make a temporary file out of an email

cat |  sed 's/$//'>$EMAILFILE 


# Get the email address to send a confirmation to, and telephone number(s) to send faxes to
SUBJLINE=`grep -m 1 "Subject:" $EMAILFILE`
#TOLINE=`grep -m 1 "To:" $EMAILFILE.1`
SENDER=`grep -m 1 "From:" $EMAILFILE | sed -e "s/From://"`
NUMBERS=`echo $SUBJLINE | awk '{print NF}'`
SUBJECT=`echo $SUBJLINE | sed -e "s/Subject://"`

# Extract PDF attachment
ripmime -v -i $DATADIR/emailfile.eml -d $DATADIR
if [[ $(find "$DATADIR"/*.dat | grep winmail.dat) ==  "" ]]; 
then 
ATTNAME=$(find "$DATADIR/" -type f -name "*.pdf" | cut -f5 -d "/"| cut -f1 -d ".")
old=$ATTNAME
new=${old//[ ]/_}
mv "$DATADIR/$old.pdf" $DATADIR/$new.pdf
ATTNAME=$(find "$DATADIR/" -type f -name "*.pdf" | cut -f5 -d "/"| cut -f1 -d ".")
else
tnef $DATADIR/emailfile.eml -C $DATADIR/
tnef $DATADIR/winmail.dat -C $DATADIR/
ATTNAME=$(find "$DATADIR/"  -type f -name "*.pdf" | cut -f5 -d "/"| cut -f1 -d ".")
old=$ATTNAME
new=${old//[ ]/_}
mv "$DATADIR/$old.pdf" $DATADIR/$new.pdf
ATTNAME=$(find "$DATADIR/"  -type f -name "*.pdf" | cut -f5 -d "/"| cut -f1 -d ".")
fi

/usr/bin/pdftops $DATADIR/$ATTNAME.pdf      >>$LOGFILE
cat $DATADIR/$ATTNAME.pdf | gs -q -sDEVICE=tiffg3 -sPAPERSIZE=a4 -r204x196 -dNOPAUSE -sOutputFile=/var/spool/asterisk/fax-outgoing/$ATTNAME.tif - >>$LOGFILE
chown asterisk /var/spool/asterisk/fax-outgoing/$ATTNAME.tif
#cat $DATADIR/$ATTNAME | gs -q -sDEVICE=tiffg3 -sPAPERSIZE=a4 -r204x196 -dNOPAUSE -sOutputFile=$DATADIR/$ATTNAME.tif - >>$LOGFILE



# Convert fax numbers from the subject field to separate numbers
SUBJLINE=`grep -m 1 "Subject:" $EMAILFILE | sed -e "s/Subject://" -e "s/[-() ]//g" -e "s/,/ /g"`

for FAXNUM in $SUBJLINE
do
[ ! -z `echo "$FAXNUM" | sed -e "s/[0-9]//g"` ] && echo "Wrong fax number: $FAXNUM" >>$LOGFILE && FAXNUM=
[ -n "$FAXNUM" ] && NEWNUM="$NEWNUM $FAXNUM"
done
FAXNUMBERS=`echo $NEWNUM | sed -e "s/ /, /g"`

cat <<EOF >>$MESSAGEFILE
From: $FAXMAIL
To:$SENDER
Subject: $NEWSUBJECT

Aacom Email to Fax Services.
EOF

SNDR1=${SENDER//[<]/}
SNDR=${SNDR1//[>]/}
if grep -q $SNDR /usr/local/bin/emaillist.txt;
then
# Create a .call file for asterisk
FAXDATE=`date +%s-%N`
cat <<EOF >$DATADIR/fax-$FAXDATE.call
Channel: $CHANNEL/$FAXNUM
MaxRetries: 2
WaitTime: 20
Context: fax-outgoing
Extension: s
Priority: 1
Set: FAXFILE=/var/spool/asterisk/fax-outgoing/$ATTNAME.tif
Set: FAXHEADER="aacom"
Set: TIMESTAMP=timestamp() { date +"%T" }
Set: DESTINATION=$FAXNUM
Set: LOCALID=099543777
Set: EMAIL=info@aacom.co.il
EOF


# Pass tiff file to asterisk

cp $DATADIR/fax-$FAXDATE.call $DATADIR/fax-$FAXDATE.call.copy
chown asterisk $DATADIR/fax-$FAXDATE.call
mv $DATADIR/fax-$FAXDATE.call $OUTGOINGDIR
sleep 2m
if [ -z "$(tail -n 20 /var/log/asterisk/full | grep SUCCESS | grep $ATTNAME)" ]; then
cat <<EOF >>$MESSAGEFILE
There was an error while sendeing the fax. 
Please try again or contact aacom's support at: 099543777.

Remember to add only one attachment of PDF file, and put your destination number on the
Subject. please leave the email body empty. 
if the fax still failes, the fax might be to large, try to split it into two faxes.


Aacom Email to Fax Services.
EOF
send_msg 0
cat <<EOF >> $LOGFILE
fax faild
EOF
del_temp
else
cat <<EOF >>$MESSAGEFILE
The fax was sent successfuly!

Aacom Email to Fax Services.
EOF


cat <<EOF >> $LOGFILE
fax succseded!
EOF
del_temp
fi

else 
cat <<EOF >> $LOGFILE
$SENDER is not in the list! not sending fax
EOF
cat <<EOF >>$MESSAGEFILE
Sorry, your email address is not listed on this service.
If you think this is a mistake, please contact support@aacom.co.il or call 099543777.

Aacom Email to Fax Services.
EOF
fi
cat $MESSAGEFILE | sendmail -t
del_temp