ARG language

FROM ubuntu AS base
RUN apt udate
RUN mkdir /home/doron
WORKDIR /home/doron

FROM base as branch-version-python
RUN apt install python
COPY ./scripts/pyfile.py .
ENTRYPOINT ["python", "./pyfile.py"]

FROM base as branch-version-bash
COPY ./scripts/bashfilr.sh .
ENTRYPOINT ["bash", "./bashfile.sh"]

FROM base as branch-version-all
RUN apt install python
COPY ./scripts/pyfile.py .
COPY ./scripts/bashfilr.sh .
ENTRYPOINT ["bash", "./allscritps.sh"]

FROM branch-version-${language} AS final
